FROM ubuntu:bionic

RUN apt update -y \
    && apt install -y \
          python3 \
          python3-flask \
          python3-flask-restful \
          python3-pymongo \
          python3-redis


COPY snaptext.py /

EXPOSE 80/tcp

ENTRYPOINT ["/usr/bin/python3", "/snaptext.py"]
